env:
  global:
    - CC_TEST_REPORTER_ID=787a2f89b15c637323c7340d65ec17e898ac44480706b4b4122ea040c2a88f1d
language: ruby
dist: trusty
cache: bundler
script: bundle exec rspec
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - ruby-head
  - rbx-3.81
  - jruby-19mode
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-3.81
    - rvm: jruby-19mode # JRuby in 1.9 mode
    - rvm: jruby-head
  fast_finish: true
  include:
    - rvm: 2.5
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
